[package]
edition.workspace = true
name              = "miden-multisig-coordinator-engine"
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bon                               = { workspace = true }
dissolve-derive                   = { workspace = true }
miden-client                      = { workspace = true, features = ["sqlite", "tonic"] }
miden-falcon-sign-test            = { git = "https://github.com/rotorship/miden-falcon-sign-test.git" }
miden-multisig-client             = { workspace = true }
miden-multisig-coordinator-domain = { workspace = true }
miden-multisig-coordinator-store  = { workspace = true }
miden-objects                     = { workspace = true }
thiserror                         = { workspace = true }
tokio                             = { workspace = true, default-features = false, features = ["sync"] }
tracing                           = { workspace = true }
url                               = { workspace = true }
