[package]
edition.workspace = true
name              = "miden-multisig-coordinator-domain"
publish.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["serde"]
serde   = ["chrono/serde", "dep:serde", "uuid/serde"]

[dependencies]
bon             = { workspace = true }
chrono          = { workspace = true }
dissolve-derive = { workspace = true }
miden-client    = { workspace = true }
miden-objects   = { workspace = true }
serde           = { workspace = true, optional = true, default-features = false, features = ["derive"] }
strum           = { version = "0.27", features = ["derive"] }
uuid            = { workspace = true }
