[workspace.package]
version = "0.0.1-pre"
edition = "2024"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "3"
members = [
  "bin/coordinator/*",
  "crates/*",
]

[workspace.dependencies]
miden-multisig-client = { path = "crates/rust-client"}
miden-multisig-coordinator-api = { path = "bin/coordinator/api" }
miden-multisig-coordinator-store = { path = "bin/coordinator/store" }

miden-client = "0.11"
miden-tx = "0.11"
thiserror = "2"
tokio = "1"
tracing = "0.1"
