[workspace.package]
version = "0.0.1-pre"
edition = "2024"
publish = false

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace]
resolver = "3"
members = [
  "bin/*",
  "crates/*",
]

[workspace.dependencies]
miden-multisig-store = { path = "bin/store" }
miden-multisig-api = { path = "bin/api" }
miden-client = { version = "0.10" }

tokio = "1"
tracing = "0.1"
