[package]
name = "miden-multisig-coordinator-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
miden-multisig-coordinator-api = { workspace = true }
miden-multisig-coordinator-store = { workspace = true }
tokio = { workspace = true, features = ["full"] }
