[package]
name = "miden-multisig-coordinator-api"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axum = "0.7"
const-hex = "1"
hyper = "1"
miden-client = { workspace = true, features = ["testing", "tonic", "sqlite"] }
miden-multisig-client = { workspace = true }
miden-multisig-coordinator-store = { workspace = true }
miden-objects = "0.11"
miden-tx = { workspace = true }
miden-falcon-sign-test = { git = "https://github.com/rotorship/miden-falcon-sign-test.git" }
rand = { version = "0.9" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha3 = "0.10"
thiserror = "2"
tokio = { workspace = true, features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
tracing = { workspace = true }
tracing-subscriber = "0.3"
