[package]
edition.workspace = true
name              = "miden-multisig-coordinator-store"
publish.workspace = true
version.workspace = true

[dependencies]
bon                               = { workspace = true }
bytes                             = { workspace = true }
chrono                            = { workspace = true }
diesel                            = { version = "2", features = ["chrono", "uuid"] }
diesel-async                      = { version = "0.7", features = ["deadpool", "postgres"] }
diesel-derive-enum                = { version = "2.1", features = ["postgres"] }
dissolve-derive                   = { workspace = true }
futures                           = { version = "0.3", default-features = false }
itertools                         = "0.14"
miden-client                      = { workspace = true }
miden-multisig-coordinator-domain = { workspace = true }
miden-objects                     = { workspace = true }
oblux                             = "0.1"
thiserror                         = { workspace = true }
tracing                           = { workspace = true }
uuid                              = { workspace = true }
